# -*- coding: utf-8 -*-
"""Librería externa de Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJddUghwKdNqPyU5un64SZXB3j6x83w-
"""

!pip install pandas

import pandas as pd

def cargar_datos():
    ruta = input("Nombre del archivo CSV: ")
    try:
        df = pd.read_csv(ruta)
        print("Archivo cargado ")
        return df
    except:
        print("Error al cargar archivo ")
        return None

def analizar(df):
    col = input("Columna numérica: ")
    if col in df.columns:
        print("Promedio:", df[col].mean())
        print("Máximo:", df[col].max())
        print("Mínimo:", df[col].min())
    else:
        print("Columna no existe ")

df = None

while True:
    print("\n1. Cargar datos")
    print("2. Analizar columna")
    print("3. Salir")

    op = input("Opción: ")

    if op == "1":
        df = cargar_datos()
    elif op == "2":
        if df is not None:
            analizar(df)
        else:
            print("Primero carga datos")
    elif op == "3":
        break